language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true

env:
  global:
    - secure: "nAZPE4kysMbIPCSAOqxFLteSJDkRVAhgPsCBzWdIEFCnqEcqHqZCLKe61ulvymO8LmpsmD4aT//eKVuhANIGaiD4wig1wO8oImPev/cyBTG6XiZuHJtRHoGf3ZiCN19fgyQwEUHdcLWKK0mB9862tTxeFEdr1rDtgibLf+0LtqNJxdH3DZ8HOOcAiizUiM5qIxdpCePPnDSiprayiAow5kygdd3ElaGaARkLN5+7aeVjaHoFPDasGccMxC2sSZKjevI1L2dbWKeAmwktRb39f0PY5QnTx+VgIGCI6wpFwQQdxOVQVKqNufQolCVV/YXBzvgV0evDzKD8Val51F4wdZcOTWzAWui622jddmt32TYzq5CwWhOlFBsDzlwgkiQ6gYa4KGbW/MCQ/eBT+FP+3rbL6YZdKiQiyuvnGLaqW6k0brKqJcz0MkDidHLzzCzfaCSNKqgXW9N2AqDKStbMso7ZnvZey6VQW6KOAy99SRuhOLodcds9uAgF+2p9omFT3JTcvL9/pLFscuBbBNeFKF74NJ6FXe1H2FbZTPOuiRVdBGfKRSX2HrTCIMfwcmTBR3Iu1ZmrYYg/0HjJE2bxd+41GER7TL07/H9krhtW0EKgUK4WjCmUwJaIxaqMLhNvH0grYKpXkhhHcZKm4d5rWWbWR5F57Y05PzxfQ/78FrQ="
    - secure: "sE7B0852wJbt0AqVm4QIzHS/l+ji/uH36y+7PboGDZg8MbDqSWw0ayvv2HJjGcH1uaYE/uDltQoEQKvciynatEGgQ2BEMS9HvS4pb8xzr1XPGDIBgC2vM6alPdS8rvQB/BgS3mQEerXUzdVfW/rgIjcDLpNfu1GfCtEZO3AiZLFhdp2HuTs3Nr9xqHj34rSVCZFLuLpz604BCQUjVADc8OwxSz/npqwoTloMFRc49JiTEu96h1tW8t5kqQHbvxP8lJcE7PpEYmZx8eye+puBQVJlGaE3wVZoQk1rVrPeP72XpArWAaMD7yfLEAnjDdb7rcgdxK95KkNYDK+O+4wMwuyFMg5cXwBvy12w+gMcElRq3zqiiDJ1ig+7kkkmAk1UAYyjME4xzh93wbEcqpE1UXhGoyOjlOYyfAFXSQLByz0aWf33JpgqXtkXerste2RNGXCz+In4XcDS3tuHppdTrKZtNjW4w96mw/0X/KJDwI6FCtyPGYPScbShuq5UqiMCQ2OpdAP+Wuh96ffn6W4HNK4aqD27DFyy31D73grlRU6LANwOZjNhcj76aQTeCYbmKivicw9seYUittDOtZ08QaoejWnvcebbBb33NX7Mk0XHBh0rHxDP20K5Om7we9ZpQ6nYbqsY2/kHdmsqh332bs8xuCNyi5w824cIZesQlw4="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./travis.sh
